name: Teradata web design system CI

on:
  pull_request:
    branches: [main, beta]

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run format:check -- --base=${{ github.event.pull_request.base.sha }}
      - run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx nx affected --target=test --base=${{ github.event.pull_request.base.sha }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx nx affected --target=build --base=${{ github.event.pull_request.base.sha }}
      - name: Deploy Storybook Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: dist/storybook/react-components
          preview-branch: gh-pages
          umbrella-dir: storybook-previews